services:
  mysql_db:
    image: mysql:8.0
    container_name: db1_fire_catalog_c
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db1_fire_catalog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
  
  postgres_db:
    image: postgres:16
    container_name: db2_urban_exposure_c
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db2_urban_exposure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  mongo_db:
    image: mongo:7
    container_name: db3_atmosphere_feed_c
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: db3_atmosphere_feed
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - db_network

networks:
  db_network:
    name: smokecast_db_network
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  mongodb_data:
